# Generated by Django 3.1.5 on 2021-02-01 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_in', models.CharField(max_length=50, null=True)),
                ('y_in', models.CharField(max_length=50, null=True)),
                ('z_in', models.CharField(max_length=50, null=True)),
                ('sys_in', models.CharField(choices=[('4326', 'WGS84'), ('4978', 'Cartesian'), ('32645', 'UTM/45'), ('32646', 'UTM/46'), ('32647', 'UTM/47'), ('32648', 'UTM/48'), ('32649', 'UTM/49'), ('32650', 'UTM/50'), ('115', 'TM/45'), ('116', 'TM/46'), ('117', 'TM/47'), ('118', 'TM/48'), ('119', 'TM/49'), ('120', 'TM/50')], default='WGS84', max_length=50)),
                ('wgs_in', models.CharField(choices=[('0', 'dms'), ('1', 'ddd')], default='dms', max_length=50)),
                ('x_out', models.CharField(blank=True, max_length=50, null=True)),
                ('y_out', models.CharField(blank=True, max_length=50, null=True)),
                ('z_out', models.CharField(blank=True, max_length=50, null=True)),
                ('sys_out', models.CharField(choices=[('4326', 'WGS84'), ('4978', 'Cartesian'), ('32645', 'UTM/45'), ('32646', 'UTM/46'), ('32647', 'UTM/47'), ('32648', 'UTM/48'), ('32649', 'UTM/49'), ('32650', 'UTM/50'), ('115', 'TM/45'), ('116', 'TM/46'), ('117', 'TM/47'), ('118', 'TM/48'), ('119', 'TM/49'), ('120', 'TM/50')], default='WGS84', max_length=50)),
                ('out_dec', models.CharField(blank=True, max_length=5, null=True)),
                ('wgs_out', models.CharField(choices=[('0', 'dms'), ('1', 'ddd')], default='dms', max_length=50)),
                ('dec_out', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=50)),
                ('conv_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_lfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vx', models.DecimalField(decimal_places=5, max_digits=5)),
                ('vy', models.DecimalField(decimal_places=5, max_digits=5)),
                ('vz', models.DecimalField(decimal_places=5, max_digits=5)),
                ('epoch', models.CharField(blank=True, max_length=100, null=True)),
                ('sigx', models.DecimalField(decimal_places=5, max_digits=5)),
                ('sigy', models.DecimalField(decimal_places=5, max_digits=5)),
                ('sigz', models.DecimalField(decimal_places=5, max_digits=5)),
                ('sigvx', models.DecimalField(decimal_places=5, max_digits=5)),
                ('sigvy', models.DecimalField(decimal_places=5, max_digits=5)),
                ('sigvz', models.DecimalField(decimal_places=5, max_digits=5)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.DecimalField(decimal_places=5, max_digits=5)),
                ('y', models.DecimalField(decimal_places=5, max_digits=5)),
                ('z', models.DecimalField(decimal_places=5, max_digits=5)),
                ('site', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='site_identify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monument_ins', models.CharField(blank=True, max_length=100, null=True)),
                ('iers_number', models.CharField(blank=True, max_length=9, null=True)),
                ('cdp_number', models.CharField(blank=True, max_length=4, null=True)),
                ('monument_desc', models.CharField(choices=[('Concrete', 'Бетон/арматур'), ('Polar/mast', 'Төмөр/Ган'), ('Etc', 'Бусад')], default='Бетон/арматур', max_length=100)),
                ('H_monumet', models.DecimalField(decimal_places=5, max_digits=5)),
                ('monument_foundation', models.CharField(choices=[('Steel rods', 'Ган тулгуур'), ('Concrete block', 'Бетон хавтан'), ('Roof', 'Барилгын дээвэр'), ('Etc', 'Бусад')], default='Ул чулуу', max_length=100)),
                ('H_depth', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Marker_Description', models.CharField(choices=[('CHISELLED CROSS', 'Хэрээс'), ('BRASS NAIL', 'Товгор'), ('DIVOT', 'Цэг'), ('Etc', 'Бусад')], default='Хэрээс', max_length=50)),
                ('Date_Installed', models.DateField()),
                ('Geologic_Characteristic', models.CharField(choices=[('BEDROCK', 'Ул чулуу'), ('CLAY', 'Шаварлаг'), ('CONGLOMERATE', 'Конгломерат'), ('GRAVEL', 'Хайрга'), ('SAND', 'Элсэрхэг'), ('Etc', 'Бусад')], default='Ул чулуу', max_length=50)),
                ('Bedrock_Type', models.CharField(choices=[('IGNEOUS', 'Галт уулын чулуулаг (IGNEOUS)'), ('METAMORPHIC', 'Хувирсан чулуулаг (METAMORPHIC)'), ('SEDIMENTARY', 'Тунамал чулуулаг')], default='Тунамал чулуулаг', max_length=50)),
                ('Bedrock_Condition', models.CharField(choices=[('FRESH', 'Шинэ/залуу'), ('JOINTED', 'Үет'), ('WEATHERED', 'Өгөршсөн')], default='Шинэ/залуу', max_length=50)),
                ('Fracture_Spacing', models.CharField(choices=[('1-10 cm', '1-10 cm'), ('11-50 cm', '11-50 cm'), ('51-200 cm', '51-200 cm'), ('over 200 cm', '200 cm дээш')], default='1-10 cm', max_length=50)),
                ('Fault_zones_nearby', models.CharField(choices=[('Bulnai', 'Булнай'), ('Hangain_nuruu', 'Хангайн нуруу')], default='Булнай', max_length=50)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamit.model_lfile')),
            ],
        ),
        migrations.CreateModel(
            name='site_hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver', models.CharField(blank=True, max_length=100, null=True)),
                ('Receiver_SN', models.CharField(blank=True, max_length=100, null=True)),
                ('Antenna_Radome', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Data_Available', models.CharField(blank=True, max_length=100, null=True)),
                ('Constellation', models.CharField(blank=True, max_length=100, null=True)),
                ('Data_Center', models.CharField(blank=True, max_length=100, null=True)),
                ('Station_Log', models.FileField(blank=True, upload_to='static/site_log', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['log'])])),
                ('left', models.ImageField(blank=True, upload_to='static/site_log')),
                ('right', models.ImageField(blank=True, upload_to='static/site_log')),
                ('north', models.ImageField(blank=True, upload_to='static/site_log')),
                ('east', models.ImageField(blank=True, upload_to='static/site_log')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamit.model_lfile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('asuult', models.TextField(max_length=100)),
                ('answered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userip', models.GenericIPAddressField(null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamit.model_system')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamit.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
