# Generated by Django 3.1.5 on 2021-02-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamit', '0003_discussion_forum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='forum',
        ),
    ]
