# Generated by Django 3.1.5 on 2021-02-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamit', '0006_auto_20210204_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamit.question'),
        ),
        migrations.AlterField(
            model_name='model_lfile',
            name='x',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model_lfile',
            name='y',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model_lfile',
            name='z',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='Зочин', max_length=100),
        ),
    ]
