# Generated by Django 3.1.5 on 2021-02-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamit', '0008_auto_20210208_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_hardware',
            name='Antenna_Radome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site_hardware',
            name='Constellation',
            field=models.CharField(choices=[('G', 'G'), ('GR', 'G/R'), ('GRE', 'G/R/E'), ('GREC', 'G/R/E/C'), ('GREZ', 'G/R/E/Z'), ('GRC', 'G/R/C')], default='G/R', max_length=50),
        ),
        migrations.AlterField(
            model_name='site_hardware',
            name='Receiver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site_hardware',
            name='Receiver_SN',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
