# Generated by Django 3.1.5 on 2021-03-19 14:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gamit', '0011_auto_20210208_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_hardware',
            name='left',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[180, 200], upload_to='static/site_log'),
        ),
        migrations.AlterField(
            model_name='site_hardware',
            name='north',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[180, 200], upload_to='static/site_log'),
        ),
        migrations.AlterField(
            model_name='site_hardware',
            name='right',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[180, 200], upload_to='static/site_log'),
        ),
        migrations.AlterField(
            model_name='site_hardware',
            name='south',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[180, 200], upload_to='static/site_log'),
        ),
    ]
