# Generated by Django 3.1.5 on 2021-03-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamit', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
